// Generated by CoffeeScript 1.7.0

/*
 */

(function() {
  var Counter, EventEmitter, Readable, callback, count, counter, readable;

  EventEmitter = require('events').EventEmitter;

  Counter = function(init) {
    this.increment = function() {
      init++;
      this.emit('incremented', init);
      return this;
    };
    return this;
  };

  Counter.prototype = new EventEmitter();

  counter = new Counter(10);

  callback = function(count) {
    console.log(count);
    return this;
  };

  counter.on('incremented', callback);

  counter.increment();

  counter.increment();

  counter.removeListener('incremented', callback);

  counter.increment();


  /*
   */

  Readable = require('stream').Readable;

  readable = new Readable();

  count = 0;

  readable._read = function() {
    if (++count > 10) {
      readable.push(null);
    }
    setTimeout(function() {
      readable.push(count + '\n');
      return this;
    }, 500);
    console.log(readable.pipe(process.stdout));
    return this;
  };


  /*
   */

}).call(this);
