// Generated by CoffeeScript 1.7.0
(function() {
  var Counter, EventEmitter, callback, counter;

  EventEmitter = require('events').EventEmitter;

  Counter = function(init) {
    this.increment = function() {
      init++;
      this.emit('incremented', init);
      return this;
    };
    return this;
  };

  Counter.prototype = new EventEmitter();

  counter = new Counter(10);

  callback = function(count) {
    console.log(count);
    return this;
  };

  counter.on('incremented', callback);

  counter.increment();

  counter.increment();

}).call(this);
