// Generated by CoffeeScript 1.7.0
(function() {
  (function($) {
    var Member, member;
    Member = void 0;
    member = void 0;
    Member = Backbone.Model.extend({
      initialize: function() {
        console.log("A new 'member' object was created...");
      },
      defaults: {
        name: "John Doe",
        age: 23
      }
    });
    member = new Member();
    console.log(member.get('name'));
    member.set('name', 'Vredesbyrdann');
    console.log(member.get('name'));
  })(jQuery);

}).call(this);
